apiVersion: v1
kind: Service
metadata:
  name: zeromq-service
  labels:
    name: zeromq
spec:
  ports:
    - port: 5559
      name: frontend-port
      targetPort: 5559
      protocol: TCP 
    - port: 5560
      name: backend-port
      targetPort: 5560
      protocol: TCP
  selector:
    name: zeromq-pod
